version: '3'

services:
    api:
      image: cyclus_api
      ports:
        - 3001:3000
      depends_on:
        - redis
        - db
      environment:
        - RAILS_ENV=production
    db:
      image: postgres:alpine
      environment:
        - POSTGRES_USER=cyclus
        - POSTGRES_PASSWORD=cyclus
        - PGDATA=/data
      volumes:
        - ~/data/cyclus:/data
    redis:
      image: redis:alpine
    worker:
      image: cyclus_worker
      depends_on:
        - redis
        - db
      environment:
        - RAILS_ENV=production
